import { body, param } from "express-validator";
import { TestController } from "./controller/test/TestController.js";
import { AdminController } from "./controller/admin/AdminController.js";
import { EmployeeController } from "./controller/employee/EmployeeController.js";

export const Routes = [
  {
    method: "get",
    route: "/",
    auth: false,
    controller: TestController,
    action: "one",
    validation: [],
  },
  {
    method: "post",
    route: "/admin/login",
    auth: false,
    controller: AdminController,
    action: "login",
    validation: [],
  },
  {
    method: "post",
    route: "/employee/login",
    auth: false,
    controller: EmployeeController,
    action: "login",
    validation: [],
  },
  {
    method: "post",
    route: "/employee/createticket",
    auth: true,
    controller: EmployeeController,
    action: "createTicket",
    validation: [],
  },
  {
    method: "post",
    route: "/admin/createemployee",
    auth: true,
    controller: AdminController,
    action: "createEmployee",
    validation: [],
  },
  {
    method: "get",
    route: "/admin/getallemployee",
    auth: true,
    controller: AdminController,
    action: "getAllEmployee",
    validation: [],
  },
  {
    method: "delete",
    route: "/admin/deleteallemployee",
    auth: true,
    controller: AdminController,
    action: "deleteAllEmployee",
    validation: [],
  },
  {
    method: "delete",
    route: "/admin/deleteemployee/:id",
    auth: true,
    controller: AdminController,
    action: "deleteEmployee",
    validation: [],
  },
  {
    method: "delete",
    route: "/admin/deleteticket/:id",
    auth: true,
    controller: AdminController,
    action: "deleteTicket",
    validation: [],
  },
  {
    method: "delete",
    route: "/admin/deleteallticket",
    auth: true,
    controller: AdminController,
    action: "deleteAllTicket",
    validation: [],
  },
  {
    method: "get",
    route: "/admin/getallticket",
    auth: true,
    controller: AdminController,
    action: "getAllTicket",
    validation: [],
  },
  {
    method: "put",
    route: "/admin/approvedenyticket/:id",
    auth: true,
    controller: AdminController,
    action: "approveDenyTicket",
    validation: [],
  },
  {
    method: "put",
    route: "/employee/closeticket/:id",
    auth: true,
    controller: EmployeeController,
    action: "closeTicket",
    validation: [],
  },
];
