import { AdminController } from "./controller/admin/AdminController.js";
import { EmployeeController } from "./controller/employee/EmployeeController.js";
import { GeneralController } from "./controller/general/GeneralController.js";
import { TestController } from "./controller/test/TestController.js";

export const Routes = [
  {
    method: "get",
    route: "/",
    auth: false,
    controller: TestController,
    action: "one",
    type: "test",
    validation: [],
  },
  {
    method: "post",
    route: "/api/admin/login",
    auth: false,
    controller: AdminController,
    action: "login",
    type: "admin",
    validation: [],
  },
  {
    method: "post",
    route: "/api/admin/createemployee",
    auth: true,
    controller: AdminController,
    action: "createEmployee",
    type: "admin",
    validation: [],
  },
  {
    method: "get",
    route: "/api/admin/getallemployee",
    auth: true,
    controller: AdminController,
    action: "getAllEmployee",
    type: "admin",
    validation: [],
  },
  {
    method: "post",
    route: "/api/admin/getallemployeepagination",
    auth: true,
    controller: AdminController,
    action: "getAllEmployeePagination",
    type: "admin",
    validation: [],
  },
  {
    method: "delete",
    route: "/api/admin/deleteallemployee",
    auth: true,
    controller: AdminController,
    action: "deleteAllEmployee",
    type: "admin",
    validation: [],
  },
  {
    method: "delete",
    route: "/api/admin/deleteemployee/:id",
    auth: true,
    controller: AdminController,
    action: "deleteEmployee",
    type: "admin",
    validation: [],
  },
  {
    method: "delete",
    route: "/api/admin/deleteticket/:id",
    auth: true,
    controller: AdminController,
    action: "deleteTicket",
    type: "admin",
    validation: [],
  },
  {
    method: "delete",
    route: "/api/admin/deleteallticket",
    auth: true,
    controller: AdminController,
    action: "deleteAllTicket",
    type: "admin",
    validation: [],
  },
  {
    method: "get",
    route: "/api/admin/getallticket",
    auth: true,
    controller: AdminController,
    action: "getAllTicket",
    type: "admin",
    validation: [],
  },
  {
    method: "post",
    route: "/api/admin/getallticketpagination",
    auth: true,
    controller: AdminController,
    action: "getAllTicketPagination",
    type: "admin",
    validation: [],
  },
  {
    method: "post",
    route: "/api/admin/getallquerypagination",
    auth: true,
    controller: AdminController,
    action: "getQueryPagination",
    type: "admin",
    validation: [],
  },
  {
    method: "get",
    route: "/api/admin/getonequery/:id",
    auth: true,
    controller: AdminController,
    action: "getOneQuery",
    type: "admin",
    validation: [],
  },

  {
    method: "get",
    route: "/api/admin/getemployee/:id",
    auth: true,
    controller: AdminController,
    action: "getEmployee",
    type: "admin",
    validation: [],
  },
  {
    method: "get",
    route: "/api/employee/getemployee/:id",
    auth: true,
    controller: EmployeeController,
    action: "getEmployee",
    type: "employee",
    validation: [],
  },
  {
    method: "post",
    route: "/api/employee/login",
    auth: false,
    controller: EmployeeController,
    action: "login",
    type: "employee",
    validation: [],
  },
  {
    method: "post",
    route: "/api/employee/createticket",
    auth: true,
    controller: EmployeeController,
    action: "createTicket",
    type: "employee",
    validation: [],
  },
  {
    method: "get",
    route: "/api/admin/getticket/:id",
    auth: true,
    controller: AdminController,
    action: "getTicket",
    type: "admin",
    validation: [],
  },
  {
    method: "get",
    route: "/api/employee/getticket/:id",
    auth: true,
    controller: EmployeeController,
    action: "getTicket",
    type: "employee",
    validation: [],
  },
  {
    method: "post",
    route: "/api/employee/getticketinmyname",
    auth: true,
    controller: EmployeeController,
    action: "getTicketInMyName",
    type: "employee",
    validation: [],
  },
  {
    method: "post",
    route: "/api/employee/getticketinmynamepagination",
    auth: true,
    controller: EmployeeController,
    action: "getTicketInMyNamePagination",
    type: "employee",
    validation: [],
  },
  {
    method: "post",
    route: "/api/admin/getdeptwiseticket",
    auth: true,
    controller: AdminController,
    action: "getDeptWiseTicket",
    type: "admin",
    validation: [],
  },
  {
    method: "post",
    route: "/api/admin/getstatuswiseticket",
    auth: true,
    controller: AdminController,
    action: "getStatusWiseTicket",
    type: "admin",
    validation: [],
  },
  {
    method: "post",
    route: "/api/admin/getpositionwiseemployee",
    auth: true,
    controller: AdminController,
    action: "getPositionWiseEmployee",
    type: "admin",
    validation: [],
  },
  {
    method: "post",
    route: "/api/admin/getgenderwiseemployee",
    auth: true,
    controller: AdminController,
    action: "getGenderWiseEmployee",
    type: "admin",
    validation: [],
  },
  {
    method: "post",
    route: "/api/admin/getdeptwiseemployee",
    auth: true,
    controller: AdminController,
    action: "getDeptWiseEmployee",
    type: "admin",
    validation: [],
  },
  {
    method: "post",
    route: "/api/employee/getticketraisedbyme",
    auth: true,
    controller: EmployeeController,
    action: "getTicketRaisedByMe",
    type: "employee",
    validation: [],
  },
  {
    method: "post",
    route: "/api/employee/getticketinmynamedeptwise",
    auth: true,
    controller: EmployeeController,
    action: "getTicketInMyNameDeptWise",
    type: "employee",
    validation: [],
  },
  {
    method: "post",
    route: "/api/employee/getticketinmynamedeptwise",
    auth: true,
    controller: EmployeeController,
    action: "getTicketInMyNameStatusWise",
    type: "employee",
    validation: [],
  },
  {
    method: "post",
    route: "/api/employee/getticketraisedbymepagination",
    auth: true,
    controller: EmployeeController,
    action: "getTicketRaisedByMePagination",
    type: "employee",
    validation: [],
  },
  {
    method: "post",
    route: "/api/employee/getticketraisedbymedeptwise",
    auth: true,
    controller: EmployeeController,
    action: "getTicketRaisedByMeDeptWise",
    type: "employee",
    validation: [],
  },
  {
    method: "post",
    route: "/api/employee/getticketraisedbymestatuswise",
    auth: true,
    controller: EmployeeController,
    action: "getTicketRaisedByMeStatusWise",
    type: "employee",
    validation: [],
  },
  {
    method: "post",
    route: "/api/sendqueryfeedback",
    auth: false,
    controller: GeneralController,
    action: "sendQueryFeedback",
    type: "general",
    validation: [],
  },
  {
    method: "get",
    route: "/api/admin/getquery",
    auth: true,
    controller: AdminController,
    action: "getQuery",
    type: "admin",
    validation: [],
  },
  {
    method: "put",
    route: "/api/employee/approvedenyticket/:id",
    auth: true,
    controller: EmployeeController,
    action: "approveDenyTicket",
    type: "employee",
    validation: [],
  },
  {
    method: "put",
    route: "/api/admin/approvedenyticket/:id",
    auth: true,
    controller: AdminController,
    action: "approveDenyTicket",
    type: "admin",
    validation: [],
  },
  {
    method: "put",
    route: "/api/admin/updateemployee/:id",
    auth: true,
    controller: AdminController,
    action: "updateEmployee",
    type: "admin",
    validation: [],
  },
  {
    method: "put",
    route: "/api/employee/closeticket/:id",
    auth: true,
    controller: EmployeeController,
    action: "closeTicket",
    type: "employee",
    validation: [],
  },
];
